const permissions = Object.freeze({
  // 👤 USER
  CREATE_USER: "CREATE_USER",
  VIEW_USER: "VIEW_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  // 🎓 STUDENT
  CREATE_STUDENT: "CREATE_STUDENT",
  VIEW_STUDENT: "VIEW_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",

  // 👨‍🏫 TEACHER
  VIEW_TEACHER: "VIEW_TEACHER",

  // 📚 CLASS / SUBJECT
  CREATE_CLASS: "CREATE_CLASS",
  VIEW_CLASS: "VIEW_CLASS",
  CREATE_SUBJECT: "CREATE_SUBJECT",
  VIEW_SUBJECT: "VIEW_SUBJECT",

  // 📅 ATTENDANCE
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",

  // 🧪 EXAM MODULE
  CREATE_EXAM: "CREATE_EXAM",
  VIEW_EXAM: "VIEW_EXAM",
  UPDATE_EXAM: "UPDATE_EXAM",
  DELETE_EXAM: "DELETE_EXAM",

  // 📝 MARKS / RESULT ENTRY
  CREATE_MARKS: "CREATE_MARKS",
  UPDATE_MARKS: "UPDATE_MARKS",
  VIEW_MARKS: "VIEW_MARKS",

  // 📊 RESULTS
  VIEW_RESULT: "VIEW_RESULT",
  GENERATE_RESULT: "GENERATE_RESULT",

  // 📈 REPORT CARD
  VIEW_REPORT_CARD: "VIEW_REPORT_CARD",
  GENERATE_REPORT_CARD: "GENERATE_REPORT_CARD",

  // 🧮 GPA / CGPA
  VIEW_GPA: "VIEW_GPA",
  VIEW_CGPA: "VIEW_CGPA",
});

export default permissions;